version: '3'
services:
  # for development purposes
  tests: &tests
    build: .
    command: ['composer', 'ci']

  dev:
    build: .
    image: keboola/processor-strip-null
    volumes:
      - ./:/code
      - ./data:/data
